import axios from 'axios';
import fs from 'fs';

export default async (sock, msg, args) => {
    const from = msg.key.remoteJid;
    const prompt = args.join(" ");

    if (!prompt) {
        return sock.sendMessage(from, { text: "❌ Please provide a description!" });
    }

    if (!fs.existsSync('./media')) {
        fs.mkdirSync('./media');
    }

    try {
        await sock.sendMessage(from, { react: { text: "🎨", key: msg.key } });

        const { key } = await sock.sendMessage(from, { text: "🚀 Asura AI is imagining..." });
        await new Promise(resolve => setTimeout(resolve, 1500));
        await sock.sendMessage(from, { text: "👺 Asura MD AI Artwork Ready!", edit: key });

        const aiUrl = `https://pollinations.ai/p/${encodeURIComponent(prompt)}?width=1024&height=1024&seed=${Math.floor(Math.random() * 100000)}`;
        
        // ഇമേജ് ഡൗൺലോഡ് ചെയ്യുന്നു
        const response = await axios.get(aiUrl, { responseType: 'arraybuffer' });
        const imageBuffer = Buffer.from(response.data);

        const aiMsg = `*👺⃝⃘̉̉̉━━━━━━━━━◆◆◆◆◆*
*┊ ┊ ┊ ┊ ┊*
*┊ ┊ ✫ ˚㋛ ⋆｡ ❀*
*┊ ☪︎⋆*
*⊹* 🪔 *ᴀꜱᴜʀᴀ ᴍᴅ ᴀɪ ᴀʀᴛ*
*✧* 「 \`👺Asura MD\` 」
*╰──────────❂*
*Generated by advanced 👺Asura MD Intelligence! ✨*

╭╌❲ *Text To Image* ❳
╎ ⊙ 𝙿𝚛𝚘𝚖𝚙𝚝 : ${prompt}
╎ ⊙ 𝙴𝚗𝚐𝚒𝚗𝚎 : Stable Diffusion
╎ ⊙ 𝚀𝚞𝚊𝚕𝚒𝚝𝚢: Ultra HD
╰╌╌╌╌╌╌╌╌╌╌࿐
╠━━━━━━━━━❥❥❥
┃ *owner* arun.Cumar 
╚━━━⛥❖⛥━━━❥❥❥
> 📢 Join our channel: https://whatsapp.com/channel/0029VbB59W9GehENxhoI5l24
> *© ᴄʀᴇᴀᴛᴇᴅ ʙʏ 👺Asura MD*`;

        // 🚀 ഇമേജ് അയക്കുന്നു (Mimetype ചേർത്തു)
        await sock.sendMessage(from, { 
            image: imageBuffer, 
            caption: aiMsg,
            mimetype: 'image/jpeg' 

        }, { quoted: msg });

        await sock.sendMessage(from, { react: { text: "✅", key: msg.key } });

    } catch (e) {
        console.error("AI Error:", e);
        await sock.sendMessage(from, { text: "❌ Error! AI ." });
    }
};
