import axios from 'axios';
import fs from 'fs';

export default async (sock, msg, args) => {
    const from = msg.key.remoteJid;
    const prompt = args.join(" ");

    if (!prompt) {
        return sock.sendMessage(from, { text: "❌ Please provide a description!" });
    }

    // media folder ഉണ്ടെന്ന് ഉറപ്പാക്കുന്നു
    if (!fs.existsSync('./media')) {
        fs.mkdirSync('./media');
    }

    try {
        await sock.sendMessage(from, { react: { text: "🎨", key: msg.key } });

        const { key } = await sock.sendMessage(from, { text: "🚀 Asura MD AI is imagining..." });
        
        // ആനിമേഷൻ
        await new Promise(resolve => setTimeout(resolve, 1500));
        await sock.sendMessage(from, { text: "👺 Asura MD AI Art Work Ready!", edit: key });

        // API Key ആവശ്യമില്ലാത്ത Pollinations AI URL
        const aiUrl = `https://pollinations.ai/p/${encodeURIComponent(prompt)}?width=1024&height=1024&seed=${Math.floor(Math.random() * 100000)}&nologo=true`;
        
        const tempPath = `./media/ai_${Date.now()}.jpg`;

        // ഇമേജ് ഡൗൺലോഡ് ചെയ്ത് ഫയലായി സേവ് ചെയ്യുന്നു
        const response = await axios({
            method: 'get',
            url: aiUrl,
            responseType: 'arraybuffer'
        });
        
        fs.writeFileSync(tempPath, response.data);

        const aiMsg = `*👺⃝⃘̉̉̉━━━━━━━━━◆◆◆◆◆*
*┊ ┊ ┊ ┊ ┊*
*┊ ┊ ✫ ˚㋛ ⋆｡ ❀*
*┊ ☪︎⋆*
*⊹* 🪔 *ᴀꜱᴜʀᴀ ᴍᴅ ᴀɪ ᴀʀᴛ*
*✧* 「 \`👺Asura MD\` 」
*╰──────────❂*
*Generated by advanced 👺Asura MD Intelligence! ✨*

╭╌❲ *Text To Image* ❳
╎ ⊙ 𝙿𝚛𝚘𝚖𝚙𝚝 : ${prompt}
╎ ⊙ 𝙴𝚗𝚐𝚒𝚗𝚎 : Stable Diffusion
╎ ⊙ 𝚀𝚞𝚊𝚕𝚒𝚝𝚢: Ultra HD
╰╌╌╌╌╌╌╌╌╌╌࿐
╠━━━━━━━━━❥❥❥
┃ *owner* arun.Cumar 
╚━━━⛥❖⛥━━━❥❥❥
> 📢 Join our channel: https://whatsapp.com/channel/0029VbB59W9GehENxhoI5l24
> *© ᴄʀᴇᴀᴛᴇᴅ ʙʏ 👺Asura MD*`;

        // 🛠️ വാട്സാപ്പ് സപ്പോർട്ട് ചെയ്യുന്ന രീതിയിൽ അയക്കുന്നു
        await sock.sendMessage(from, { 
            image: { url: tempPath }, 
            caption: aiMsg 
        }, { quoted: msg });

        // മെമ്മറി ലാഭിക്കാൻ ഫയൽ ഡിലീറ്റ് ചെയ്യുന്നു
        setTimeout(() => {
            if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
        }, 5000); 

        await sock.sendMessage(from, { react: { text: "✅", key: msg.key } });

    } catch (e) {
        console.error("AI Error:", e);
        await sock.sendMessage(from, { text: "❌error." });
    }
};
