import gis from 'g-i-s';

export default async (sock, msg, args) => {
    const chat = msg.key.remoteJid;
    const query = args.join(' ');

    if (!query) return sock.sendMessage(chat, { text: "🔍 Searching?\n Example: *.Search* mummy" }, { quoted: msg });

    try {
        // --- Google Image Search (g-i-s) ---
        gis(query, async (error, results) => {
            if (error) {
                console.error(error);
                return sock.sendMessage(chat, { text: "❌ error!" });
            }

            if (!results || results.length === 0) {
                return sock.sendMessage(chat, { text: "❌ Error!" });
            }

            // ആദ്യത്തെ ചിത്രം എടുക്കുന്നു
            const firstImage = results[0].url;

            let replyText = `🌟 *ASURA GOOGLE SEARCH* 🌟\n\n`;
            replyText += `*Query:* ${query}\n\n`;
            
            replyText += `*Top Results Found:* \n`;
            results.slice(0, 5).forEach((res, index) => {
                replyText += `\n*${index + 1}. Result Image*`;
                replyText += `\n🔗 ${res.url}\n`;
            });

            replyText += `\n\n_Generated by ASURA AI - No Download System_`;

            // ചിത്രവും വിവരങ്ങളും അയക്കുന്നു
            await sock.sendMessage(chat, { 
                image: { url: firstImage }, 
                caption: replyText 
            }, { quoted: msg });
        });

    } catch (e) {
        console.error("GIS Error:", e);
        await sock.sendMessage(chat, { text: "❌ Error!" });
    }
};
