import gis from 'g-i-s';

export default async (sock, msg, args) => {
    const chat = msg.key.remoteJid;
    const query = args.join(' ');

    if (!query) return sock.sendMessage(chat, { text: "🔍 Example: .search who is cr7" }, { quoted: msg });

    try {
       
        gis(query, async (error, results) => {
            if (error || !results || results.length === 0) {
                return sock.sendMessage(chat, { text: "❌ error!" });
            }

            const firstResult = results[0];
            const imageUrl = firstResult.url;

            let infoText = `📖 *INFORMATION: ${query.toUpperCase()}*\n\n`;
            
            infoText += `📌 *Result:* ${query} 🙂.\n\n`;
            
            // കൂടുതൽ വിവരങ്ങൾക്കായി ആദ്യ 3-4 റിസൾട്ടുകളുടെ ടൈറ്റിൽ/വിവരണം ചേർക്കാം
            results.slice(0, 3).forEach((res, index) => {
                if(res.width && res.height) {
                    infoText += `🔹 Source Data ${index + 1}: ${query} details analyzed.\n`;
                }
            });

            infoText += `\n_Generated by ASURA MD_`;

            // ചിത്രവും വിവരവും അയക്കുന്നു
            await sock.sendMessage(chat, { 
                image: { url: imageUrl }, 
                caption: Asura MD 
            }, { quoted: msg });
        });

    } catch (e) {
        console.error("Search Error:", e);
        await sock.sendMessage(chat, { text: "❌ Error" });
    }
};
